version: '3'

services:
  darmontajkhizotapi:
    build: .
    ports:
      - "5281:5281"
    container_name: 'darmontajkhizot.api'
    networks:
      - darmontajkhizot-network

networks:
  darmontajkhizot-network: 
    driver: bridge