version: '3'

services:
  darmontajkhizotapi:
    build: .
    ports:
      - "5000:5000"
    image: "darmontajkhizot.api"
    container_name: 'darmontajkhizot.api'
    env_file:
      - .env
    networks:
      - darmontajkhizot-network

networks:
  darmontajkhizot-network:
    driver: bridge


