version: '3'

services:
  darmontajkhizotapi:
    build: .
    ports:
      - "5000:5000"
    image: "darmontajkhizot.api"
    container_name: 'darmontajkhizot.api'
    env_file:
      - .env
    networks:
      - darmontajkhizot-network
  db:
    image: postgres:13
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - darmontajkhizot-data:/var/lib/postgresql/data
    networks:
      - darmontajkhizot-network

networks:
  darmontajkhizot-network:
    driver: bridge

volumes:
  darmontajkhizot-data:
    driver: local

